---
title: "Analisis"
author: "J Davyt-Colo"
date: "1/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Librerias

```{r}
library(tidyverse)
library(lubridate)
```

## Data

```{r}
library(lubridate)

encuestaA_May_30 <- read_csv(here::here("Pilots/Superintendencia_de_Pensiones/data/30052022/encuestaA_May 30.csv")) %>% 
  mutate(fecha = lubridate::as_date(EndDate, format = "%Y-%m-%d"),
         sitioderivado = stringi::stri_sub(UID, -1),
         useridn = as.numeric(useridn)) %>%
  dplyr::filter(fecha  == "2022-05-20" | fecha  == "2022-05-27") %>%
  filter(is.na(useridn)==FALSE) %>%
  select(-StartDate,
         -EndDate,
         -Status,
         -IPAddress,
         -Progress,
         -`Duration (in seconds)`,
         -Finished,
         -RecordedDate,
         -ResponseId,
         -RecipientLastName,
         -RecipientFirstName,
         -RecipientEmail,
         -ExternalReference,
         -LocationLatitude,
         -LocationLongitude,
         -DistributionChannel,
         -UserLanguage) %>% distinct()
encuestaA_May_30 <- encuestaA_May_30[,colSums(is.na(encuestaA_May_30))<nrow(encuestaA_May_30)]


encuestaB_Privada_May30 <- read_csv(here::here("Pilots/Superintendencia_de_Pensiones/data/30052022/encuestaB_Privada_May30.csv")) %>% 
  mutate(fecha = lubridate::as_date(EndDate, format = "%Y-%m-%d"),
         encuesta = "B_Privada",
         uemail = as.numeric(uemail)) %>%
  dplyr::filter(fecha  == "2022-05-20" | fecha  == "2022-05-27") %>%
  filter(is.na(uemail)==FALSE) %>%
  select(fecha,
         encuesta,
         contains("Comp"),
         uemail, 
         UID,
         InfoUtil_1, 
         InfoAbruma2_1, 
         Curiosity_1, 
         Confidence_1 , 
         total_reward)
encuestaB_Privada_May30 <- encuestaB_Privada_May30[,colSums(is.na(encuestaB_Privada_May30))<nrow(encuestaB_Privada_May30)]

encuestaB_Publica_May30 <- read_csv(here::here("Pilots/Superintendencia_de_Pensiones/data/30052022/encuestaB_Publica_May30.csv")) %>% 
  mutate(fecha = lubridate::as_date(EndDate, format = "%Y-%m-%d"),
         encuesta = "B_Publica",
         uemail = as.numeric(uemail))  %>%
  dplyr::filter(fecha  == "2022-05-20" | fecha  == "2022-05-27") %>%
  filter(is.na(uemail)==FALSE) %>%
  select(fecha,
         encuesta,
         contains("Comp"),
         uemail, 
         UID,
         InfoUtil_1, 
         InfoAbruma2_1, 
         Curiosity_1, 
         Confidence_1 , 
         total_reward)
encuestaB_Publica_May30 <- encuestaB_Publica_May30[,colSums(is.na(encuestaB_Publica_May30))<nrow(encuestaB_Publica_May30)]

encuestaC_Privada_May30 <- read_csv(here::here("Pilots/Superintendencia_de_Pensiones/data/30052022/encuestaC_Privada_May30.csv")) %>% 
  mutate(fecha = lubridate::as_date(EndDate, format = "%Y-%m-%d"),
         encuesta = "C_Privada",
         uemail = as.numeric(uemail)) %>%
  dplyr::filter(fecha  == "2022-05-20" | fecha  == "2022-05-27") %>%
  filter(is.na(uemail)==FALSE) %>%
  select(fecha,
         encuesta,
         contains("Comp"),
         uemail, 
         UID,
         InfoUtil_1, 
         InfoAbruma2_1)
encuestaC_Privada_May30 <- encuestaC_Privada_May30[,colSums(is.na(encuestaC_Privada_May30))<nrow(encuestaC_Privada_May30)]

encuestaC_Publica_May30 <- read_csv(here::here("Pilots/Superintendencia_de_Pensiones/data/30052022/encuestaC_Publica_May30.csv")) %>% 
  mutate(fecha = lubridate::as_date(EndDate, format = "%Y-%m-%d"),
         encuesta = "C_Publica",
         uemail = as.numeric(uemail)) %>%
  dplyr::filter(fecha  == "2022-05-20" | fecha  == "2022-05-27") %>%
  filter(is.na(uemail)==FALSE) %>%
  select(fecha,
         encuesta,
         contains("Comp"),
         uemail, 
         UID,
         InfoUtil_1, 
         InfoAbruma2_1,)
encuestaC_Publica_May30 <- encuestaC_Publica_May30[,colSums(is.na(encuestaC_Publica_May30))<nrow(encuestaC_Publica_May30)]
```

```{r}
encuestaB_Privada_May30 <- encuestaB_Privada_May30 %>%
  mutate(
    ncomp1 = ifelse(Comp1.RP=="No", 1, 0),
    ncomp2=ifelse(Comp2.RP=="Solicitar el Certificado de Saldo en la AFP", 1, 0),
    ncomp3=ifelse(Comp3.RP=="No", 1, 0),
    ncomp4=ifelse(Comp4.RP=="Para comparar todas las ofertas de pensión disponibles en un sólo lugar", 1, 0),
    ncomp5=ifelse(Comp5.RP=="Sí", 1, 0),
    ncomp6=ifelse(Comp6.RP=="Es voluntario", 1, 0),
    ncomp7=ifelse(Comp7.RP=="El/la afiliado/a", 1, 0),
    ncomp8=ifelse(Comp1.RV=="No", 1, 0),
    ncomp9=ifelse(Comp2.RV=="Solicitar el Certificado de Saldo en la AFP", 1, 0),
    ncomp10=ifelse(Comp3.RV=="No", 1, 0),
    ncomp11=ifelse(Comp4.RV=="Para comparar todas las ofertas de pensión disponibles en un sólo lugar", 1, 0),
    ncomp12=ifelse(Comp5.RV=="Sí", 1, 0),
    ncomp13=ifelse(Comp6.RV=="Es voluntario", 1, 0),
    ncomp14=ifelse(Comp7.RV=="La Compañía de Seguros", 1, 0),
    ncomp15=ifelse(Comp1.MM=="No", 1, 0),
    ncomp16=ifelse(Comp2.MM=="Solicitar el Certificado de Saldo en la AFP", 1, 0),
    ncomp17=ifelse(Comp3.MM=="No", 1, 0),
    ncomp18=ifelse(Comp4.MM=="Para comparar todas las ofertas de pensión disponibles en un sólo lugar", 1, 0),
    ncomp19=ifelse(Comp5.MM=="Sí", 1, 0),
    ncomp20=ifelse(Comp6.MM=="Es voluntario", 1, 0),
    ncomp21=ifelse(Comp7.MM=="Ambos: la Compañía de Seguros y el/la afiliado/a", 1, 0) 
    )


ncomp<- encuestaB_Privada_May30 %>% select(contains("ncomp"))
encuestaB_Privada_May30$correct_response <-rowSums(ncomp,na.rm = T)

encuestaB_Privada_May30 <- encuestaB_Privada_May30 %>%
  mutate(
    correct_response = rowSums(ncomp, na.rm = T)
  ) %>%
  select(everything(), -contains("comp"))
rm(ncomp)

#table(encuestaB_Privada_May30$correct_response)
```

```{r}
encuestaB_Publica_May30 <- encuestaB_Publica_May30 %>%
  mutate(
    ncomp1<-ifelse(Comp1.PP=="A partir de los 65 años", 1, 0),
    ncomp2<-ifelse(Comp2.PP=="Tener ClaveÚnica", 1, 0),
    ncomp3<-ifelse(Comp3.PP=="Sí", 1, 0),
    ncomp4<-ifelse(Comp4.PP=="A través del Estado con los impuestos", 1, 0),
    ncomp5<-ifelse(Comp5.PP=="Por encontrarse dentro del 9% de mayores ingresos", 1, 0),
    ncomp6<-ifelse(Comp6.PP=="No", 1, 0),
    ncomp7<-ifelse(Comp7.PP=="$1.000.000", 1, 0)
  )

ncomp<- encuestaB_Publica_May30 %>% select(contains("ncomp"))

encuestaB_Publica_May30 <- encuestaB_Publica_May30 %>%
  mutate(
    correct_response = rowSums(ncomp, na.rm = T)
  ) %>%
  select(everything(), -contains("comp"))
rm(ncomp)
```

```{r}
segundas_encuestas <- bind_rows(encuestaB_Privada_May30, encuestaB_Publica_May30,
                            encuestaC_Publica_May30)
```


```{r}
encuestas <- encuestaA_May_30 %>%
  left_join(segundas_encuestas, by = c("useridn" = "uemail"))  %>%
  mutate(second = ifelse(is.na(encuesta)==TRUE, "sin segunda encuesta", encuesta))
encuestas <- encuestas[,colSums(is.na(encuestas))<nrow(encuestas)]
```


```{r}
delete.na <- function(DF, n=0) {
  DF[rowSums(is.na(DF)) <= n,]
}
#get data
sitios <-
  list.files(path = here::here("Pilots/Superintendencia_de_Pensiones/data/30052022"),
             pattern = "Clicks", 
             full.names = T) %>% 
  map_df(~read_csv(., col_types = cols(.default = "c"))) %>%
  unite("inicio_wix", c("inicio_wix.p1", "inicio_wix.p2", "inicio_wix.p3", "inicio_wix.p4", "inicio_wix.p5", "inicio_wix.p6"), na.rm = TRUE, remove = FALSE)

sitios <- sitios[,colSums(is.na(sitios))<nrow(sitios)]

sitios <- delete.na(sitios, 184)

sitios <- sitios %>%
  mutate(useridn = as.numeric(gsub("-", "" , substr(userid, 1,4))),
         sitio= stringi::stri_sub(userid, -1),
         fecha = lubridate::as_date(`Created date`, format = "%Y-%m-%d"))  %>%
  filter(useridn != 0)

sitios2 <- sitios %>%
  select(-contains("inicio_wix")) %>%
  mutate(na_count = apply(., 1, function(x) sum(is.na(x)))) %>%
  mutate(n_clicks = dim(.)[2]-na_count-4)
```

```{r}
pilot_data <- encuestas %>%
  full_join(sitios2, by = "useridn") %>% 
  filter(useridn != 0) %>%
  mutate(Age = 2022 - as.numeric(Birth))
```

## Analysis {.tabset}

### Some plots

```{r}
pilot_data %>%
ggplot(aes(y = n_clicks, x = as.factor(sitio))) +
geom_boxplot()
```



```{r}
p1 <- pilot_data %>%
ggplot(aes(y = n_clicks, x = as.factor(sitio))) +
  geom_jitter() +
  stat_boxplot()

p2 <- pilot_data %>%
ggplot(aes(y = n_clicks, x = as.factor(sitio), color = factor(Gender))) +
  geom_jitter() +
  stat_boxplot()
p3 <- pilot_data %>%
ggplot(aes(y = n_clicks, x = as.factor(sitio), color = factor(Gender))) +
  geom_jitter() +
  stat_boxplot()
gridExtra::grid.arrange( p1, p2)
```


```{r}
plot(pilot_data$Age)
```


```{r}
zi <- pilot_data %>% filter(useridn != 0)  %>% group_by(useridn) %>% summarise(n = n())
```

### Dependent Variables




