---
title: "data_management"
author: "J Davyt-Colo"
date: "26/5/2022"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```


```{r}
library(tidyverse)
```


## Encuestas

```{r}
# Get data
df1 <- read_csv(here::here("Pilots/Superintendencia_de_Pensiones/data/Encuesta_A.csv"))[-1:-2,]
df2 <- read_csv(here::here("Pilots/Superintendencia_de_Pensiones/data/Encuesta_B_Publica.csv"))[-1:-2,]
df3 <- read_csv(here::here("Pilots/Superintendencia_de_Pensiones/data/Encuesta_B_Privada.csv"))[-1:-2,]
df4 <- read_csv(here::here("Pilots/Superintendencia_de_Pensiones/data/Encuesta_C_Privada.csv"))[-1:-2,]
df5 <- read_csv(here::here("Pilots/Superintendencia_de_Pensiones/data/Encuesta_C_Publica.csv"))[-1:-2,]

################# Clean #######################################333
drop<-c(    "StartDate", "EndDate", "Status", "IPAddress", "Progress","Duration (in seconds)", "Finished", "RecordedDate", 
            "ResponseId", "RecipientLastName", "RecipientFirstName",  "RecipientEmail", "ExternalReference", 
            "LocationLatitude", "LocationLongitude", "DistributionChannel", "UserLanguage")

df1<-df1[,!(names(df1) %in% drop)]
df2<-df2[,!(names(df2) %in% drop)]
df3<-df3[,!(names(df3) %in% drop)]
df4<-df4[,!(names(df4) %in% drop)]
df5<-df5[,!(names(df5) %in% drop)]



### Correct responses 

#Public Pensions
#library(tidyverse)

comp<- df2 %>% select(contains("Comp"))

comp$ncomp1<-ifelse(df2$Comp1.PP=="A partir de los 65 años", 1, 0)
comp$ncomp2<-ifelse(df2$Comp2.PP=="Tener ClaveÚnica", 1, 0)
comp$ncomp3<-ifelse(df2$Comp3.PP=="Sí", 1, 0)
comp$ncomp4<-ifelse(df2$Comp4.PP=="A través del Estado con los impuestos", 1, 0)
comp$ncomp5<-ifelse(df2$Comp5.PP=="Por encontrarse dentro del 9% de mayores ingresos", 1, 0)
comp$ncomp6<-ifelse(df2$Comp6.PP=="No", 1, 0)
comp$ncomp7<-ifelse(df2$Comp7.PP=="$1.000.000", 1, 0)

ncomp<- comp %>% select(contains("ncomp"))
comp$correct_response <-rowSums(ncomp, na.rm = T)
df2$correct_response<-comp$correct_response
rm(comp, ncomp)


### Pensiones privadas

comp<- df3 %>% select(contains("Comp"))

comp$ncomp1<-ifelse(df3$Comp1.RP=="No", 1, 0)
comp$ncomp2<-ifelse(df3$Comp2.RP=="Solicitar el Certificado de Saldo en la AFP", 1, 0)
comp$ncomp3<-ifelse(df3$Comp3.RP=="No", 1, 0)
comp$ncomp4<-ifelse(df3$Comp4.RP=="Para comparar todas las ofertas de pensión disponibles en un sólo lugar", 1, 0)
comp$ncomp5<-ifelse(df3$Comp5.RP=="Sí", 1, 0)
comp$ncomp6<-ifelse(df3$Comp6.RP=="Es voluntario", 1, 0)
comp$ncomp7<-ifelse(df3$Comp7.RP=="El/la afiliado/a", 1, 0)


comp$ncomp8<-ifelse(df3$Comp1.RV=="No", 1, 0)
comp$ncomp9<-ifelse(df3$Comp2.RV=="Solicitar el Certificado de Saldo en la AFP", 1, 0)
comp$ncomp10<-ifelse(df3$Comp3.RV=="No", 1, 0)
comp$ncomp11<-ifelse(df3$Comp4.RV=="Para comparar todas las ofertas de pensión disponibles en un sólo lugar", 1, 0)
comp$ncomp12<-ifelse(df3$Comp5.RV=="Sí", 1, 0)
comp$ncomp13<-ifelse(df3$Comp6.RV=="Es voluntario", 1, 0)
comp$ncomp14<-ifelse(df3$Comp7.RV=="La Compañía de Seguros", 1, 0) 


comp$ncomp15<-ifelse(df3$Comp1.MM=="No", 1, 0)
comp$ncomp16<-ifelse(df3$Comp2.MM=="Solicitar el Certificado de Saldo en la AFP", 1, 0)
comp$ncomp17<-ifelse(df3$Comp3.MM=="No", 1, 0)
comp$ncomp18<-ifelse(df3$Comp4.MM=="Para comparar todas las ofertas de pensión disponibles en un sólo lugar", 1, 0)
comp$ncomp19<-ifelse(df3$Comp5.MM=="Sí", 1, 0)
comp$ncomp20<-ifelse(df3$Comp6.MM=="Es voluntario", 1, 0)
comp$ncomp21<-ifelse(df3$Comp7.MM=="Ambos: la Compañía de Seguros y el/la afiliado/a", 1, 0) 


ncomp<- comp %>% select(contains("ncomp"))
comp$correct_response <-rowSums(ncomp,na.rm = T)
df3$correct_response<-comp$correct_response
rm(comp, ncomp)



######## Merge datasets

#DV

dvars<-c("uemail", "UID" ,"InfoUtil_1", "InfoAbruma2_1", "Curiosity_1", "Confidence_1" , "total_reward", "correct_response" )

dv2<-df2[,(names(df2) %in% dvars)]
dv3<-df3[,(names(df3) %in% dvars)]

dv<-rbind(dv2, dv3)


df<-merge(df1, dv, by.x = "useridn", by.y = "uemail", all = T)
```

```{r}
library(lubridate)
encuestaA_May_30 <- read_csv(here::here("Pilots/Superintendencia_de_Pensiones/data/30052022/encuestaA_May 30.csv")) %>% 
  mutate(fecha = lubridate::as_date(EndDate, format = "%Y-%m-%d")) %>%
  dplyr::filter(fecha  == "2022-05-20" | fecha  == "2022-05-27") %>%
  filter(is.na(useridn)==FALSE) %>%
  select(-StartDate,
         -EndDate,
         -Status,
         -IPAddress,
         -Progress,
         -`Duration (in seconds)`,
         -Finished,
         -RecordedDate,
         -ResponseId,
         -RecipientLastName,
         -RecipientFirstName,
         -RecipientEmail,
         -ExternalReference,
         -LocationLatitude,
         -LocationLongitude,
         -DistributionChannel,
         -UserLanguage)
encuestaA_May_30 <- encuestaA_May_30[,colSums(is.na(encuestaA_May_30))<nrow(encuestaA_May_30)]


encuestaB_Privada_May30 <- read_csv(here::here("Pilots/Superintendencia_de_Pensiones/data/30052022/encuestaB_Privada_May30.csv")) %>% 
  mutate(fecha = lubridate::as_date(EndDate, format = "%Y-%m-%d")) %>%
  dplyr::filter(fecha  == "2022-05-20" | fecha  == "2022-05-27") %>%
  filter(is.na(uemail)==FALSE) %>%
  select(-StartDate,
         -EndDate,
         -Status,
         -IPAddress,
         -Progress,
         -`Duration (in seconds)`,
         -Finished,
         -RecordedDate,
         -ResponseId,
         -RecipientLastName,
         -RecipientFirstName,
         -RecipientEmail,
         -ExternalReference,
         -LocationLatitude,
         -LocationLongitude,
         -DistributionChannel,
         -UserLanguage)
encuestaB_Privada_May30 <- encuestaB_Privada_May30[,colSums(is.na(encuestaB_Privada_May30))<nrow(encuestaB_Privada_May30)]

encuestaB_Publica_May30 <- read_csv(here::here("Pilots/Superintendencia_de_Pensiones/data/30052022/encuestaB_Publica_May30.csv")) %>% 
  mutate(fecha = lubridate::as_date(EndDate, format = "%Y-%m-%d")) %>%
  filter(is.na(uemail)==FALSE) %>%
  select(-StartDate,
         -EndDate,
         -Status,
         -IPAddress,
         -Progress,
         -`Duration (in seconds)`,
         -Finished,
         -RecordedDate,
         -ResponseId,
         -RecipientLastName,
         -RecipientFirstName,
         -RecipientEmail,
         -ExternalReference,
         -LocationLatitude,
         -LocationLongitude,
         -DistributionChannel,
         -UserLanguage)
encuestaB_Publica_May30 <- encuestaB_Publica_May30[,colSums(is.na(encuestaB_Publica_May30))<nrow(encuestaB_Publica_May30)]

encuestaC_Privada_May30 <- read_csv(here::here("Pilots/Superintendencia_de_Pensiones/data/30052022/encuestaC_Privada_May30.csv")) %>% 
  mutate(fecha = lubridate::as_date(EndDate, format = "%Y-%m-%d")) %>%
  dplyr::filter(fecha  == "2022-05-20" | fecha  == "2022-05-27") %>%
  filter(is.na(uemail)==FALSE) %>%
  select(-StartDate,
         -EndDate,
         -Status,
         -IPAddress,
         -Progress,
         -`Duration (in seconds)`,
         -Finished,
         -RecordedDate,
         -ResponseId,
         -RecipientLastName,
         -RecipientFirstName,
         -RecipientEmail,
         -ExternalReference,
         -LocationLatitude,
         -LocationLongitude,
         -DistributionChannel,
         -UserLanguage)
encuestaC_Privada_May30 <- encuestaC_Privada_May30[,colSums(is.na(encuestaC_Privada_May30))<nrow(encuestaC_Privada_May30)]

encuestaC_Publica_May30 <- read_csv(here::here("Pilots/Superintendencia_de_Pensiones/data/30052022/encuestaC_Publica_May30.csv")) %>% 
  mutate(fecha = lubridate::as_date(EndDate, format = "%Y-%m-%d")) %>%
  dplyr::filter(fecha  == "2022-05-20" | fecha  == "2022-05-27") %>%
  filter(is.na(uemail)==FALSE) %>%
  select(-StartDate,
         -EndDate,
         -Status,
         -IPAddress,
         -Progress,
         -`Duration (in seconds)`,
         -Finished,
         -RecordedDate,
         -ResponseId,
         -RecipientLastName,
         -RecipientFirstName,
         -RecipientEmail,
         -ExternalReference,
         -LocationLatitude,
         -LocationLongitude,
         -DistributionChannel,
         -UserLanguage)
encuestaC_Publica_May30 <- encuestaC_Publica_May30[,colSums(is.na(encuestaC_Publica_May30))<nrow(encuestaC_Publica_May30)]
```

```{r}
encuestas <- encuestaA_May_30 %>%
  left_join(encuestaB_Privada_May30, by = c("useridn" = "uemail")) %>%
  left_join(encuestaB_Publica_May30, by = c("useridn" = "uemail")) %>%
  left_join(encuestaC_Publica_May30, by = c("useridn" = "uemail")) 
encuestas <- encuestas[,colSums(is.na(encuestas))<nrow(encuestas)]
```

## Sitios

```{r}
delete.na <- function(DF, n=0) {
  DF[rowSums(is.na(DF)) <= n,]
}
#get data
sitios <-
  list.files(path = here::here("Pilots/Superintendencia_de_Pensiones/data/30052022"),
             pattern = "Clicks", 
             full.names = T) %>% 
  map_df(~read_csv(., col_types = cols(.default = "c"))) %>%
  unite("inicio_wix", c("inicio_wix.p1", "inicio_wix.p2", "inicio_wix.p3", "inicio_wix.p4", "inicio_wix.p5", "inicio_wix.p6"), na.rm = TRUE, remove = FALSE)

sitios <- sitios[,colSums(is.na(sitios))<nrow(sitios)]

sitios <- delete.na(sitios, 184)

sitios <- sitios %>%
  mutate(useridn = gsub("-", "" , substr(userid, 1,4)),
         sitio= stringi::stri_sub(userid, -1),
         fecha = lubridate::as_date(`Created date`, format = "%Y-%m-%d"))  %>%
  filter(useridn != "0000")
```

## All data
```{r}
pilot_data <- encuestas %>%
  full_join(sitios, by = "useridn")
```

```{r}
z2 <- as.data.frame(Map(x = strsplit(names(pilot_data), '[.]+'), 
                        DATA = pilot_data, 
                        f = function(x,DATA){
                          setNames(replicate(length(x), DATA, simplify = FALSE),x  )}
))
```


## Analysis

```{r}
#personas_sin_contestar
sinc <- table(is.na(pilot_data$QRead)==TRUE)
sinc[2]
```

```{r}
#personas sin dirigirse a un sitio
sinsitio <- pilot_data %>%
  filter(is.na(pilot_data$QRead)==FALSE) %>%
  filter(is.na(`Created date`)==TRUE)
length(unique(sinsitio$useridn))
```

