---
title: "Analysis"
author: "Joselina Davyt-Colo"
date: '2022-07-05'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
## Set directory
#path <- "C:/Users/Usuario/Documents/INVESTIGACION/MiInvestigacion/Pensions-Website-Design/"
#setwd("C:/Users/Usuario/Documents/INVESTIGACION/MiInvestigacion/Pensions-Website-Design/")

## Load packages
source(paste0(path_github,"Pilots/Superintendencia_de_Pensiones/R/paquetes.R"))
```

```{r}
## Load own functions
source(paste0(path_github,"Pilots/Superintendencia_de_Pensiones/R/funciones.R"))
```



## Analysis {.tabset}

```{r}
pilot_data <- readRDS(paste0(path_datos, "pilot_data.rds"))
sitios_sm <- readRDS(paste0(path_datos, "sitios_complete.rds"))
```


```{r}
zi <- pilot_data %>% filter(useridn != 0)  %>% group_by(useridn) %>% summarise(n = n())
```


```{r}
theme_gppr <- function(){ 
    font <- "Georgia"   #assign font family up front
    
    ggthemes::theme_economist_white() %+replace%    #replace elements we want to change
    
    theme(
      legend.position = "bottom",
      #grid elements
      panel.grid.major = element_blank(),    #strip major gridlines
      panel.grid.minor = element_blank(),    #strip minor gridlines
      
      #since theme_minimal() already strips axis lines, 
      #we don't need to do that again
      
      #text elements
      plot.title = element_text(             #title
                   family = font,            #set font family
                   size = 20,                #set font size
                   face = 'bold',            #bold typeface
                   hjust = 0,                #left align
                   vjust = 2),               #raise slightly
      
      plot.subtitle = element_text(          #subtitle
                   family = font,            #font family
                   size = 14),               #font size
      
      plot.caption = element_text(           #caption
                   family = font,            #font family
                   size = 9,                 #font size
                   hjust = 1),               #right align
      
      # axis.title = element_text(             #axis titles
      #              family = font,            #font family
      #              size = 10),               #font size
      # 
      # axis.text = element_text(              #axis text
      #              family = font,            #axis famuly
      #              size = 10),                #font size
      
      #axis.text.x = element_text(            #margin for axis text
                   # margin=margin(5, b = 10)),
      #axis.title.x = element_text(size=12),
      axis.title.y = element_text(size=12, angle = 90, vjust = +3)
      
      #since the legend often requires manual tweaking 
      #based on plot content, don't define it here
    )
}
```



### Website navigation behaviors

```{r}
proporciones1 <- pilot_data %>%
 group_by(Treatments, online) %>% #group
  summarise(prop = sum(OptOut =="In")/n()) %>% #calculate proportion 
  na.omit() 
proporciones1
```

```{r}
# pilot_data %>%
#   arrange(StartDate) %>%
#   mutate(sesion = as.numeric(case_when(
#     fecha.x.x == "2022-05-20" & Time_of_day == "Morning" ~ 1,
#     fecha.x.x == "2022-05-20" & Time_of_day == "Afternoon" ~ 2,
#     fecha.x.x == "2022-05-27" & Time_of_day == "Morning" ~ 3,
#     fecha.x.x == "2022-05-27" & Time_of_day == "Afternoon" ~ 4,
#     fecha.x.x == "2022-06-07" & Time_of_day == "Morning" ~ 5,
#     fecha.x.x == "2022-06-07" & Time_of_day == "Afternoon" ~ 6,
#     fecha.x.x == "2022-06-08" & Time_of_day == "Morning" ~ 7,
#     fecha.x.x == "2022-06-08" & Time_of_day == "Afternoon" ~ 8,
#   ))) 
  

# proporciones1 %>% ggplot() +
#   theme_classic() + 
#   geom_smooth(aes(x = sesion , y = prop, color = Treatments), se = F) +
#   geom_point(aes(x = sesion, y = prop, color = Treatments)) +
#   coord_cartesian(xlim = c(1,8), ylim = c(0.8,1)) +
#   theme_gppr() +
#   ggsci::scale_color_aaas()
```


```{r}
# left_label <- "Morning"
# right_label <- "Afternoon"
# library(CGPfunctions)
# newggslopegraph(proporciones, Time_of_day, prop, Treatments)
# 
# # Plot
# pilot_data %>%
#   ggplot() +
#   geom_segment(aes(x=1, xend=2, y="Morning", yend="Afternoon", col=class), size=.75, show.legend=F) + 
#                   geom_vline(xintercept=1, linetype="dashed", size=.1) + 
#                   geom_vline(xintercept=2, linetype="dashed", size=.1) +
#                   scale_color_manual(labels = c("Up", "Down"), 
#                                      values = c("green"="#00ba38", "red"="#f8766d")) +  # color of lines
#                   labs(x="", y="Mean GdpPerCap") +  # Axis labels
#                   xlim(.5, 2.5) + ylim(0,(1.1*(max(df$`1952`, df$`1957`))))  # X and Y axis limits
```


```{r}
proporciones %>%
  ggplot(aes(x = as.factor(online), y = prop, group = Treatments, color=Treatments)) +
  geom_line(alpha = 0.6, size = 1) +
  geom_point(alpha = 0.6, size = 1) +
   theme_gppr() +
  ggsci::scale_color_aaas() 
  # xlab("Year") + ylab("Avg wind power") +
  # ggtitle("Average wind power in 1975 and 2015")
```
```{r}
proporciones2 <- pilot_data %>%
 group_by(Treatments) %>% #group
  summarise(prop = sum(OptOut =="In")/n()) %>% #calculate proportion 
  na.omit() 
proporciones2
```

```{r}
proporciones2 %>%
  ggplot(aes(x=Treatments, y=prop, fill = Treatments)) +
  geom_bar(stat="identity") +
  theme_gppr() +
  ggsci::scale_fill_aaas() +
  theme(axis.title.x=element_blank(), axis.text.x=element_blank()) +
  geom_hline(aes(yintercept = 0.8), linetype = 2, color = "gray") +
  geom_text(aes(y=0.85, label=paste0("0.8"), x=0.1), colour='gray', hjust=-0.1 , vjust = 1) +
  ylab("Opt In")
ggsave(paste0(path_github, "Pilots/Superintendencia_de_Pensiones/figures/prop.pdf"))
```


```{r}
library("viridis") 
proporciones_recomendar <- pilot_data %>%
  dplyr::select(Treatments, Recomendar_NPS_GROUP) %>%
  na.omit() %>%
  group_by(Treatments) %>% 
  summarise(prop = sum(Recomendar_NPS_GROUP =="Promotor")/n()) %>%  
  na.omit() 
#proporciones

proporciones_recomendar %>%
  ggplot(aes(x=Treatments, y=prop, fill = Treatments)) +
  geom_bar(stat="identity") +
  theme_gppr() +
  ggsci::scale_fill_aaas() +
  theme(axis.title.x=element_blank(), axis.text.x=element_blank()) +
  geom_hline(aes(yintercept = 0.3), linetype = 2, color = "gray") +
  geom_text(aes(y=0.32, label=paste0("0.3"), x=0.1), colour='gray', hjust=-0.1 , vjust = 1) +
  ylab("Promoter") +
  #coord_cartesian(ylim = c(0,0.5))
  scale_y_continuous(breaks = c(0.2, 0.40), limits=c(0,0.5)) 
ggsave(paste0(path_github,"Pilots/Superintendencia_de_Pensiones/figures/prop_promoter.pdf"))
```


```{r}
proporciones_asesor <- pilot_data %>%
  dplyr::select(Treatments, Advisor) %>%
  na.omit() %>%
  group_by(Treatments) %>% 
  summarise(prop = sum(Advisor =="No")/n()) %>%  
  na.omit() 
#proporciones

proporciones_asesor %>%
  ggplot(aes(x=Treatments, y=prop, fill = Treatments)) +
  geom_bar(stat="identity") +
  theme_gppr() +
  ggsci::scale_fill_aaas() +
  theme(axis.title.x=element_blank(), axis.text.x=element_blank()) +
  geom_hline(aes(yintercept = 0.5), linetype = 2, color = "gray") +
  geom_text(aes(y=0.55, label=paste0("0.5"), x=0.1), colour='gray', hjust=-0.1 , vjust = 1) +
  ylab("Not hire an advisor")
ggsave(paste0(path_github,"Pilots/Superintendencia_de_Pensiones/figures/prop_asesor.pdf"))
```

```{r}
pilot_data %>%
  ggplot(aes(n_clicks, tiempo_sec_1click_nclick, colour = fct_reorder2(Treatments, n_clicks, tiempo_sec_1click_nclick))) +
  geom_point(size = 2) +
  geom_line(size = 1.5) +
  ggsci::scale_color_aaas() +
  labs(colour = "Treatments") +
  theme_gppr() +
  xlab("Number of clicks") +
  ylab("Time Spend")
```





```{r, , results='asis'}
my_comparisons <- list( c("Baseline", "Perfil"), c("Perfil", "Video"), c("Video", "VideoPerfil"), c("Video", "Baseline"), c("Perfil", "VideoPerfil"), c("Baseline", "VideoPerfil") )
# 
# n_clicks_wilcox  <- ggpubr::compare_means(n_clicks ~ Treatments,  data = pilot_data, 
#                       comparisons = my_comparisons,  method = "wilcox.test")
# 
# n_clicks_wilcox %>%
#     knitr::kable(format = 'latex', booktabs = TRUE) %>%
#     kableExtra::add_header_above(header = c("Text" = 2, "Values" = 2))
```


```{r}
h <- round(mean(pilot_data$n_clicks, na.rm = TRUE), digits = 2)


symnum.args = list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 0.1, 1), 
                   symbols = c("****", "***", "**", "*",".", "ns"))

pilot_data %>%
  ggplot(aes(y = n_clicks, x = Treatments, color=Treatments)) +
  geom_boxplot() +
  geom_jitter(width=0.15) +
  ylab("Number of Clicks") +
  geom_hline(aes(yintercept = h), linetype = 2, color = "gray") +
  geom_text(aes(y=h+2, label=paste0("Mean ", prettyNum(h,big.mark=",")), x=0.1), colour='gray', hjust=-0.1 , vjust = 1) +
   
  #ggpubr::stat_compare_means(method = "anova", vjust = 1, hjust = -0.1) +      # Add global p-value
  ggpubr::stat_compare_means(comparisons = my_comparisons, 
                             label = "p.signif", method = "wilcox.test",
                             symnum.args = symnum.args) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank()) +
  scale_y_continuous(limits = c(0,50)) 
  #ggpubr::stat_compare_means(method = "wilcox.test")
  #scale_fill_distiller()
  #paletteer::scale_color_paletteer_d("colorBlindness::paletteMartin")
    #scale_colour_brewer(type = "seq", palette = "Spectral")
ggsave(paste0(path_github,"Pilots/Superintendencia_de_Pensiones/figures/n_clicks.pdf"))
```

```{r}
ggline(pilot_data, x = "Treatments", y = "n_clicks", add = "mean_se",
       color = "Gender", palette = "jco") +
  xlab("Treatments") +
  ylab("Number of Clicks") +
  ggpubr::stat_compare_means(aes(group=Gender), label = "p.signif", method = "wilcox.test") +
  scale_y_continuous(limits = c(0,50)) 
  theme_gppr()
```


```{r}
pilot_data %>%
  ggplot(aes(y = n_clicks, x = Treatments,  color = factor(Gender))) +
  geom_boxplot() +
 geom_point(position = position_jitterdodge()) +
  xlab("Treatments") +
  ylab("Number of Clicks") +
  geom_hline(aes(yintercept = h), linetype = 2, color = "gray") +
  geom_text(aes(y=h+5, label=paste0("Mean ", prettyNum(h,big.mark=",")), x=0.1), colour='gray', hjust=-0.1 , vjust = 1) +
  #geom_text(aes(h, label=h, hjust=-0.1)) +
  # geom_text(aes(y=mean(pilot_data$n_clicks),
  #               label=prettyNum(round(mean(pilot_data$n_clicks)),big.mark=","), x=1),
  #           colour='blue' )   +
  theme_gppr() +
  ggsci::scale_color_jco() + 
  stat_compare_means(aes(group = Gender), label = "p.signif") +
  scale_y_continuous(limits = c(0,50)) 
  #ggpubr::stat_compare_means(method = "wilcox.test")
  #scale_fill_distiller()
  #paletteer::scale_color_paletteer_d("colorBlindness::paletteMartin")
    #scale_colour_brewer(type = "seq", palette = "Spectral")
```

```{r, echo=TRUE}
ggpubr::compare_means(tiempo_con_video ~ Treatments,  data = sitios_sm, ref.group = "Baseline",
              method = "t.test")
```

```{r}
ggpubr::compare_means(tiempo_sec_1click_nclick ~ Treatments,  data = pilot_data, ref.group = "Baseline",
              method = "t.test")
```


```{r}
h <- round(mean(pilot_data$tiempo_sec_1click_nclick, na.rm = TRUE), digits = 1)
  
my_comparisons <- rev(list( c("Baseline", "Perfil"), c("Perfil", "Video"), c("Perfil", "VideoPerfil"), c("Video", "VideoPerfil"), c("Video", "Baseline"), c("Baseline", "VideoPerfil") ))

pilot_data %>%
  dplyr::select(tiempo_sec_1click_nclick, Treatments) %>% na.omit() %>%
  ggplot(aes(y = tiempo_sec_1click_nclick, x = Treatments, color=Treatments)) +
  geom_boxplot() +
  geom_jitter(width=0.15) +
  xlab("Treatments") +
  ylab("Time Spend (seconds)") +
  geom_hline(aes(yintercept = h), linetype = 2, color = "gray") +
  geom_text(aes(y=h+60, label=paste0("Mean ", prettyNum(h,big.mark=",")), x=0.1), colour='gray', hjust=-0.1 , vjust = 1) +
  #geom_text(aes(h, label=h, hjust=-0.1)) +
  # geom_text(aes(y=mean(pilot_data$n_clicks),
  #               label=prettyNum(round(mean(pilot_data$n_clicks)),big.mark=","), x=1),
  #           colour='blue' )   +
  theme_gppr() +
  ggsci::scale_color_aaas() + 
  ggpubr::stat_compare_means(method = "anova", vjust = 1, hjust = -0.1) +      # Add global p-value
  ggpubr::stat_compare_means(comparisons = my_comparisons, 
                             label = "p.signif", method = "wilcox.test") 

```


```{r}
h <- round(mean(sitios_sm$tiempo_con_video, na.rm = TRUE), digits = 1)
  
sitios_sm %>%
  ggplot(aes(y = tiempo_con_video, x = Treatments, color=Treatments)) +
  geom_boxplot() +
  geom_jitter(width=0.15) +
  xlab("Treatments") +
  ylab("Time Spend Per Page (seconds)") +
  geom_hline(aes(yintercept = h), linetype = 2, color = "gray") +
  geom_text(aes(y=h+60, label=paste0("Mean ", prettyNum(h,big.mark=",")), x=0.1), colour='gray', hjust=-0.1 , vjust = 1) +
  theme_gppr() +
  ggsci::scale_color_aaas() + 
  ggpubr::stat_compare_means(method = "anova", vjust = 1, hjust = -0.05) +      # Add global p-value
  ggpubr::stat_compare_means(comparisons = my_comparisons, 
                             label = "p.signif", method = "wilcox.test") 
  #ggpubr::stat_compare_means(method = "wilcox.test")
  #scale_fill_distiller()
  #paletteer::scale_color_paletteer_d("colorBlindness::paletteMartin")
    #scale_colour_brewer(type = "seq", palette = "Spectral")
```
```{r}
p <- sitios_sm %>%
  ggplot(aes(pagina, tiempo_pag)) + 
    geom_point(color = "gray")
p + geom_line(aes(group = useridn), color = "gray") +
  stat_summary(aes(group = Treatments, color = Treatments), 
                 fun.y = "mean", geom = "line", size = 2) +
  ggsci::scale_color_aaas() +
   theme_gppr() +
  theme(axis.text.x = element_text(angle = 45)) +
  scale_y_continuous(breaks =c(0, 200, 400, 600, 800, 1000), limits = c(0, 1000)) +
  xlab("Treatments") +
  ylab("Time Spend Per Page (seconds)")
 
```
```{r}
p <- sitios_sm %>%
  ggplot(aes(pagina2, tiempo_pag)) + 
    geom_point(color = "gray")
p + geom_line(aes(group = useridn), color = "gray") +
  stat_summary(aes(group = Treatments, color = Treatments), 
                 fun.y = "mean", geom = "line", size = 2) +
  ggsci::scale_color_aaas() +
   theme_gppr() +
  theme(axis.text.x = element_text(angle = 45)) +
  scale_y_continuous(breaks =c(0, 200, 400, 600, 800, 1000), limits = c(0, 1000)) +
  xlab("Treatments") +
  ylab("Time Spend Per Page (seconds)")
 
```

```{r}
sitios_sm %>%
ggplot(aes(pagina, tiempo_pag, group = Treatments, color = Treatments)) +
    geom_line(aes(group = useridn, color = Treatments), alpha = .3) +
    stat_summary(fun.data = "mean_cl_normal", geom = "errorbar", width = .1,
                 position = position_dodge(.1), color = "black") +
    stat_summary(fun.y = "mean", geom = "line", size = 1.2,
                 position = position_dodge(.1)) +
    stat_summary(fun.y = "mean", geom = "point", size = 2,
                 position = position_dodge(.1)) +
  ggsci::scale_color_aaas() +
  scale_y_continuous(breaks =c(0, 200, 400, 600, 800, 1000), limits = c(0, 1000)) +
  theme_gppr() +
  theme(axis.text.x = element_text(angle = 45)) +
  xlab("Treatments") +
  ylab("Time Spend Per Page (seconds)")
```


```{r}
sitios_sm %>%
ggplot(aes(x = pagina, y =tiempo_pag, group = Treatments, color = Treatments)) +
    geom_line(aes(group = useridn, color = Treatments), alpha = .3) +
    stat_summary(fun.data = "mean_cl_normal", geom = "errorbar", width = .1,
                 position = position_dodge(.1), color = "black") +
    stat_summary(fun.y = "mean", geom = "line", size = 1.2,
                 position = position_dodge(.1)) +
    stat_summary(fun.y = "mean", geom = "point", size = 2,
                 position = position_dodge(.1)) +
    ggsci::scale_color_aaas() +
  theme_gppr() +
  facet_wrap(~Treatments) +
  theme(strip.text.x = element_blank(),
        axis.text.x = element_text(angle = 45))
```

```{r}
pilot_data %>%
  ggplot(aes(n_clicks, tiempo_sec_1click_nclick, colour = fct_reorder2(Treatments, n_clicks, tiempo_sec_1click_nclick))) +
  geom_point(size = 2) +
  geom_line(size = 1.5) +
  ggsci::scale_color_aaas() +
  labs(colour = "Treatments") +
  theme_gppr() +
  xlab("Number of clicks") +
  ylab("Time Spend")
```


```{r}
# di <-sitios_sm %>% 
#   dplyr::select(useridn, sitio, pagina, Treatments, tiempo_con_video) %>%
#   pivot_wider(names_from = pagina, 
#               values_from = tiempo_con_video,
#               values_fn  = sum,
#               values_fill = 0) 
# gd <- sitios_sm %>% 
#         group_by(Treatments) %>% 
#         summarise(tiempo_con_video = mean(tiempo_con_video))
# 
# do <- sitios_sm %>%
#   group_by(Treatments, pagina) %>%
#   summarise(tiempo_con_video = sum(tiempo_con_video)) %>%
#   ggplot(aes(x = Treatments, y = tiempo_con_video, color = Treatments, fill = Treatments)) +
#   geom_bar(data = gd, stat = "identity", alpha = .3) +
#   ggrepel::geom_text_repel(aes(label = pagina), color = "black", size = 2.5, segment.color = "grey") +
#   geom_point() +
#   guides(color = "none", fill = "none") 
```


```{r}
g <- pilot_data %>% ggplot(aes(tiempo_min_1click_nclick, n_clicks)) 

g + geom_jitter(aes(col=Treatments)) + 
  geom_smooth(aes(col=Treatments), method="lm", se=F) +
  ggsci::scale_color_aaas() +
  theme_gppr()
```


### Correct responses

```{r, complete}
h <- round(mean(pilot_data$correct_response, na.rm = TRUE), digits = 1)
  
pilot_data %>%
  ggplot(aes(y = correct_response, x = Treatments, color=Treatments)) +
  geom_boxplot() +
  geom_jitter(width=0.15) +
  #xlab("Treatments") +
  ylab("Correct Responses") +
  geom_hline(aes(yintercept = h), linetype = 2, color = "gray") +
  geom_text(aes(y=h+0.5, label=paste0("Mean ", prettyNum(h,big.mark=",")), x=0.1), colour='gray', hjust=-0.1 , vjust = 1) +
  #geom_text(aes(h, label=h, hjust=-0.1)) +
  # geom_text(aes(y=mean(pilot_data$n_clicks),
  #               label=prettyNum(round(mean(pilot_data$n_clicks)),big.mark=","), x=1),
  #           colour='blue' )   +
  theme_gppr() +
  ggsci::scale_color_aaas() + 
  ggpubr::stat_compare_means(method = "anova", vjust = 1, hjust = -0.05) +
  theme(axis.text.x=element_blank(),
        axis.title.y = element_text(vjust = +3),
        plot.title = element_text(vjust = -1, size = 12),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank()) +
  scale_y_continuous(breaks = seq(0, 10, 2), limits = c(0,12))
ggsave(paste0(path_github,"Pilots/Superintendencia_de_Pensiones/figures/responses.pdf"))

```
```{r, heterog}
h <- round(mean(pilot_data$correct_response, na.rm = TRUE), digits = 1)
  
pilot_data %>%
  ggplot(aes(y = correct_response, x = Treatments, color = factor(Gender))) +
  geom_boxplot() +
  geom_point(position = position_jitterdodge()) +
  ylab("Correct Responses") +
  geom_hline(aes(yintercept = h), linetype = 2, color = "gray") +
  geom_text(aes(y=h+0.5, label=paste0("Mean ", prettyNum(h,big.mark=",")), x=0.1), colour='gray', hjust=-0.1 , vjust = 1) +
  theme_gppr() +
  ggsci::scale_color_jco() + 
  stat_compare_means(aes(group = Gender), label = "p.signif")+
  theme(axis.text.x=element_blank(),
        axis.title.y = element_text(vjust = +3),
        plot.title = element_text(vjust = -1, size = 12),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank()) +
  scale_y_continuous(breaks = seq(0, 10, 2), limits = c(0,12))
```

```{r}
pilot_data %>%
  ggplot(aes(n_clicks, correct_response, colour = fct_reorder2(Treatments, n_clicks, correct_response))) +
  geom_point() +
  geom_line() +
  labs(colour = "Treatments") +
  theme_gppr() +
  xlab("Number of clicks") +
  ylab("Number of Correct Response")
```
```{r}
pilot_data %>%
  ggplot(aes(tiempo_sec_1click_nclick, correct_response, colour = fct_reorder2(Treatments, tiempo_sec_1click_nclick, correct_response))) +
  geom_point() +
  geom_line() +
  labs(colour = "Treatments") +
  theme_gppr() +
  xlab("Time Spend (seconds)") +
  ylab("Number of Correct Response")
```

### Self reported measures

```{r, data}
dependent <- pilot_data %>%
  dplyr::select(correct_response, Confidence_1, InfoAbruma2_1, Curiosity_1, InfoUtil_1, tiempo_min_1click_nclick, Treatments, Gender, Pension_Type) %>%
  mutate(Treatments = as.factor(Treatments)) %>%
  mutate(Gender = as.factor(Gender)) %>%
   mutate(Pension_Type = as.factor(Pension_Type)) %>%
  mutate_if(is.character,as.numeric) 
```


```{r}
q_labs <- c("Confidence", "Curiosity", "Overwhelming information", "Utility")

dependent %>%
  mutate_if(is.factor,as.character) %>%
  mutate(Treatments = as.factor(Treatments)) %>%
  mutate_if(is.character,as.numeric) %>%
  dplyr::select(Confidence_1, InfoAbruma2_1, Curiosity_1, InfoUtil_1, Treatments) %>%
  pivot_longer(-Treatments, names_to = "question", values_to = "response") %>%
  mutate(question = factor(question, levels = c("Confidence_1", "Curiosity_1", "InfoAbruma2_1", "InfoUtil_1"), 
                  labels =c("Confidence", "Curiosity", "Overwhelming information", "Utility"))) %>%
  ggplot(aes(y = response, x = Treatments, fill=Treatments)) +
  geom_boxplot() +
  labs(x ="", y = "Response (on a 0 to 10 scale)") +
  #scale_y_discrete(limits = 0:10) +
  scale_y_continuous(breaks = seq(0, 10, 2), limits = c(0,12)) +
  theme_gppr() +
  theme(axis.ticks.x = element_blank())+
  ggsci::scale_color_aaas() +
  ggsci::scale_fill_aaas() +
  facet_wrap(~question) +
  theme(axis.text.x = element_blank())

```

```{r}
h_cu <- round(mean(dependent$Curiosity_1, na.rm = TRUE), digits = 1)
h_co <- round(mean(dependent$Confidence_1, na.rm = TRUE), digits = 1)
h_a <- round(mean(dependent$InfoAbruma2_1, na.rm = TRUE), digits = 1)
cu <- dependent %>%
  mutate_if(is.factor,as.character) %>%
  mutate(Treatments = as.factor(Treatments)) %>%
  mutate_if(is.character,as.numeric) %>%
ggplot(aes(y = Curiosity_1, x = as.factor(Treatments), color = Treatments)) +
  geom_boxplot() +
  geom_jitter() +
  geom_hline(aes(yintercept = h_cu), linetype = 2, color = "gray") +
  geom_text(aes(y=h_cu+0.5, label=paste0("Mean ", prettyNum(h_cu,big.mark=",")), x=0.1), colour='gray', hjust=-0.1 , vjust = 1) +
  scale_y_continuous(breaks = seq(0, 10, 2), limits = c(0,12)) +
  theme_gppr() +
  ggpubr::stat_compare_means(comparisons = my_comparisons, 
                             label = "p.signif", method = "wilcox.test") +
  ggsci::scale_color_aaas() +
  ggsci::scale_fill_aaas() +
  labs(x ="", y = "", title = "Curiosity")  +
  theme(axis.text.x=element_blank(),
         axis.title.y = element_text(vjust = +6),
        axis.ticks.x = element_blank(),
        plot.title = element_text(vjust = -1, size = 12))
co <- dependent %>%
  mutate_if(is.factor,as.character) %>%
  mutate(Treatments = as.factor(Treatments)) %>%
  mutate_if(is.character,as.numeric) %>%
ggplot(aes(y = Confidence_1, x = as.factor(Treatments), color = Treatments)) +
  geom_boxplot() +
  geom_jitter() +
  geom_hline(aes(yintercept = h_co), linetype = 2, color = "gray") +
  geom_text(aes(y=h_co+0.5, label=paste0("Mean ", prettyNum(h_co,big.mark=",")), x=0.1), colour='gray', hjust=-0.1 , vjust = 1) +
  scale_y_continuous(breaks = seq(0, 10, 2), limits = c(0,12)) +
  theme_gppr() +
  ggsci::scale_color_aaas() +
  ggsci::scale_fill_aaas() +
  ggpubr::stat_compare_means(comparisons = my_comparisons, 
                             label = "p.signif", method = "wilcox.test")+
  labs(x ="", y = "", title = "Confidence")  +
  theme(axis.text.x=element_blank(),
        axis.title.y = element_text(vjust = +6),
        plot.title = element_text(vjust = -1, size = 12),
        axis.ticks.x = element_blank())
abru <- dependent %>%
  mutate_if(is.factor,as.character) %>%
  mutate(Treatments = as.factor(Treatments)) %>%
  mutate_if(is.character,as.numeric) %>%
ggplot(aes(y = InfoAbruma2_1, x = as.factor(Treatments), color = Treatments)) +
  geom_boxplot() +
  geom_jitter() +
  geom_hline(aes(yintercept = h_a), linetype = 2, color = "gray") +
  geom_text(aes(y=h_a+0.5, label=paste0("Mean ", prettyNum(h_a,big.mark=",")), x=0.1), colour='gray', hjust=-0.1 , vjust = 1) +
  scale_y_continuous(breaks = seq(0, 10, 2), limits = c(0,12)) +
  theme_gppr() +
  ggsci::scale_color_aaas() +
  ggsci::scale_fill_aaas() +
  labs(x ="", y = "Too much information", title = "")  +
  ggpubr::stat_compare_means(comparisons = my_comparisons, 
                             label = "p.signif", method = "wilcox.test")+
  theme(axis.text.x=element_blank(),
        axis.title.y = element_text(vjust = +3),
        plot.title = element_text(vjust = -1, size = 12),
        axis.ticks.x = element_blank())

ggarrange(cu, co,  abru, common.legend = TRUE, legend = "bottom", ncol = 3)
```

```{r, utility}
symnum.args = list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 0.1, 1), 
                   symbols = c("****", "***", "**", "*",".", "ns"))
mis_comparaciones <- list( c("Baseline", "Perfil"), c("Perfil", "Video"), c("Video", "VideoPerfil"), c("Video", "Baseline"), c("Perfil", "VideoPerfil"), c("Baseline", "VideoPerfil") )
h_u <- round(mean(dependent$InfoUtil_1, na.rm = TRUE), digits = 1)
dependent %>%
  mutate_if(is.factor,as.character) %>%
  mutate(Treatments = as.factor(Treatments)) %>%
  mutate_if(is.character,as.numeric) %>%
ggplot(aes(y = InfoUtil_1, x = as.factor(Treatments), color = Treatments)) +
  geom_boxplot() +
  geom_jitter() +
  geom_hline(aes(yintercept = h_u), linetype = 2, color = "gray") +
  geom_text(aes(y=h_u+0.5, label=paste0("Mean ", prettyNum(h_a,big.mark=",")), x=0.1), colour='gray', hjust=-0.1 , vjust = 1)  +
  theme_gppr() +
  ggsci::scale_color_aaas() +
  ggsci::scale_fill_aaas() +
  labs(x ="", y = "Utility", title = "")  +
    ggpubr::stat_compare_means(comparisons = my_comparisons, 
                             label = "p.signif", method = "wilcox.test", 
                             hide.ns = TRUE) +
  theme(axis.text.x=element_blank(),
        axis.title.y = element_text(vjust = +3),
        plot.title = element_text(vjust = -1, size = 12),
        axis.ticks.x = element_blank()) +
  coord_cartesian(ylim = c(2,15))
ggsave(paste0(path_github,"Pilots/Superintendencia_de_Pensiones/figures/utility.pdf"))
```
```{r, toomuch}
symnum.args = list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 0.1, 1), 
                   symbols = c("****", "***", "**", "*",".", "ns"))
mis_comparaciones <- list( c("Baseline", "Perfil"), c("Perfil", "Video"), c("Video", "VideoPerfil"), c("Video", "Baseline"), c("Perfil", "VideoPerfil"), c("Baseline", "VideoPerfil") )

h_a <- round(mean(dependent$InfoAbruma2_1, na.rm = TRUE), digits = 1)


dependent %>%
  mutate_if(is.factor,as.character) %>%
  mutate(Treatments = as.factor(Treatments)) %>%
  mutate_if(is.character,as.numeric) %>%
ggplot(aes(y = InfoAbruma2_1, x = as.factor(Treatments), color = Treatments)) +
  geom_boxplot() +
  geom_jitter() +
  geom_hline(aes(yintercept = h_a), linetype = 2, color = "gray") +
  geom_text(aes(y=h_a+0.5, label=paste0("Mean ", prettyNum(h_a,big.mark=",")), x=0.1), colour='gray', hjust=-0.1 , vjust = 1)  +
  theme_gppr() +
  ggsci::scale_color_aaas() +
  ggsci::scale_fill_aaas() +
  labs(x ="", y = "Too much information", title = "")  +
  ggpubr::stat_compare_means(method = "anova", vjust = 1, hjust = -0.05) +
  # ggpubr::stat_compare_means(comparisons = mis_comparaciones, 
  #                            label = "p.signif", method = "wilcox.test",
  #                            hide.ns = TRUE)+
  theme(axis.text.x=element_blank(),
        axis.title.y = element_text(vjust = +3),
        plot.title = element_text(vjust = -1, size = 12),
        axis.ticks.x = element_blank()) +
  scale_y_continuous(breaks = seq(0, 10, 2), limits = c(0,12))
ggsave(paste0(path_github,"Pilots/Superintendencia_de_Pensiones/figures/toomuch.pdf"))
```


```{r}
h_cu <- round(mean(dependent$Curiosity_1, na.rm = TRUE), digits = 1)
h_co <- round(mean(dependent$Confidence_1, na.rm = TRUE), digits = 1)
h_a <- round(mean(dependent$InfoAbruma2_1, na.rm = TRUE), digits = 1)
cu <- dependent %>%
ggplot(aes(y = Curiosity_1, x = as.factor(Treatments), color = Gender)) +
  geom_boxplot() +
  geom_point(position = position_jitterdodge()) +
  geom_hline(aes(yintercept = h_cu), linetype = 2, color = "gray") +
  geom_text(aes(y=h_cu+0.5, label=paste0("Mean ", prettyNum(h_cu,big.mark=",")), x=0.1), colour='gray', hjust=-0.1 , vjust = 1) +
  scale_y_continuous(breaks = seq(0, 10, 2), limits = c(0,12)) +
  theme_gppr() +
 ggsci::scale_color_jco() + 
  labs(x ="Treatments", y = "", title = "Curiosity")  +
  theme(axis.title.y = element_text(vjust = +6),
        axis.ticks.x = element_blank(),
        plot.title = element_text(vjust = -1, size = 12)) +
  stat_compare_means(aes(group = Gender), label = "p.signif")
co <- dependent %>%
ggplot(aes(y = Confidence_1, x = as.factor(Treatments), color = Gender)) +
  geom_boxplot() +
  geom_point(position = position_jitterdodge()) +
  geom_hline(aes(yintercept = h_co), linetype = 2, color = "gray") +
  geom_text(aes(y=h_co+0.5, label=paste0("Mean ", prettyNum(h_co,big.mark=",")), x=0.1), colour='gray', hjust=-0.1 , vjust = 1) +
  scale_y_continuous(breaks = seq(0, 10, 2), limits = c(0,12)) +
  theme_gppr() +
  ggsci::scale_color_jco() + 
  labs(x ="Treatments", y = "Confidence", title = "")  +
  theme(axis.title.y = element_text(vjust = +6),
        plot.title = element_text(vjust = -1, size = 12),
        axis.ticks.x = element_blank())  +
  stat_compare_means(aes(group = Gender), label = "p.signif") 

abru <- dependent %>%
ggplot(aes(y = InfoAbruma2_1, x = as.factor(Treatments), color = Gender)) +
  geom_boxplot() +
  geom_point(position = position_jitterdodge()) +
  geom_hline(aes(yintercept = h_a), linetype = 2, color = "gray") +
  geom_text(aes(y=h_a+0.5, label=paste0("Mean ", prettyNum(h_a,big.mark=",")), x=0.1), colour='gray', hjust=-0.1 , vjust = 1) +
  scale_y_continuous(breaks = seq(0, 10, 2), limits = c(0,12)) +
  theme_gppr() +
  ggsci::scale_color_jco() + 
  labs(x ="Treatments", y = "", title = "Overwhelmed")  +
  theme(axis.title.y = element_text(vjust = +6),
        plot.title = element_text(vjust = -1, size = 12),
        axis.ticks.x = element_blank()) +
  stat_compare_means(aes(group = Gender), label = "p.signif")
uti <- dependent %>%
ggplot(aes(y = InfoUtil_1, x = as.factor(Treatments), color = Gender)) +
  geom_boxplot() +
  geom_point(position = position_jitterdodge()) +
  geom_hline(aes(yintercept = h_a), linetype = 2, color = "gray") +
  geom_text(aes(y=h_a+0.5, label=paste0("Mean ", prettyNum(h_a,big.mark=",")), x=0.1), colour='gray', hjust=-0.1 , vjust = 1) +
  scale_y_continuous(breaks = seq(0, 10, 2), limits = c(0,12)) +
  theme_gppr() +
  ggsci::scale_color_jco() + 
  labs(x ="Treatments", y = "Utility", title = "")  +
  theme(axis.title.y = element_text(vjust = +3),
        plot.title = element_text(vjust = -1, size = 12),
        axis.ticks.x = element_blank()) +
  stat_compare_means(aes(group = Gender), label = "p.signif")
cu
co
abru
uti
```

```{r, confidence het}
dependent %>%
ggplot(aes(y = Confidence_1, x = as.factor(Treatments), color = Gender)) +
  geom_boxplot() +
  geom_point(position = position_jitterdodge()) +
  geom_hline(aes(yintercept = h_co), linetype = 2, color = "gray") +
  geom_text(aes(y=h_co+0.5, label=paste0("Mean ", prettyNum(h_co,big.mark=",")), x=0.1), colour='gray', hjust=-0.1 , vjust = 1) +
  scale_y_continuous(breaks = seq(0, 10, 2), limits = c(0,12)) +
  theme_gppr() +
  ggsci::scale_color_jco() + 
  labs(x ="Treatments", y = "Confidence", title = "")  +
  theme(axis.title.y = element_text(vjust = +3),
        plot.title = element_text(vjust = -1, size = 12),
        axis.ticks.x = element_blank())  +
  stat_compare_means(aes(group = Gender), label = "p.signif") 

ggsave(here::here("Pilots/Superintendencia_de_Pensiones/figures/confidence_het.pdf"))
```
```{r}
h_res <- round(mean(dependent$correct_response, na.rm = TRUE), digits = 1)

dependent %>%
  dplyr::select(correct_response, Treatments, Pension_Type)  %>%
ggplot(aes(y = correct_response, x = as.factor(Treatments), color = Pension_Type)) +
  geom_boxplot() +
  geom_point(position = position_jitterdodge()) +
  geom_hline(aes(yintercept = h_res), linetype = 2, color = "gray") +
  geom_text(aes(y=h_res+0.5, label=paste0("Mean ", prettyNum(h_cu,big.mark=",")), x=0.1), colour='gray', hjust=-0.1 , vjust = 1) +
  scale_y_continuous(breaks = seq(0, 10, 2), limits = c(0,12)) +
  theme_gppr() +
 scale_colour_brewer(type = "seq", palette = "Dark2")+ 
  labs(x ="Treatments", y = "Correct Response", title = "")  +
  theme(axis.title.y = element_text(vjust = +3),
        axis.ticks.x = element_blank(),
        plot.title = element_text(vjust = -1, size = 12)) +
  stat_compare_means(aes(group = Pension_Type), label = "p.signif")
ggsave(paste0(path_github,"Pilots/Superintendencia_de_Pensiones/figures/responses_het.pdf"))

```


```{r}
pilot_data %>%
  group_by(Curiosity_1) %>%                                            # for each question number
  count(Treatments) %>%                                                  # count gender type
  mutate(Prc = round(n/sum(n),2)) %>%            # update variable
  ungroup() %>%                                                   # forget the grouping
  mutate(Prc_text = paste0(Prc*100, "%")) %>%
  ggplot(aes(Treatments, Prc, fill=factor(Curiosity_1)))+                     # plot
  geom_bar(position = "fill", stat = "identity")+                # add bars
  #geom_text(aes(label=Prc_text), position = position_dodge(width=1), size=4) +
  coord_flip() 
curiosity_count <- pilot_data %>%
  ggplot(aes(Curiosity_1)) +
  geom_bar() +
  facet_wrap(~Treatments)
curiosity_count <- curiosity_count$data

```

```{r}
pilot_data %>%
  group_by(Curiosity_1) %>%                                            # for each question number
  count(Treatments) %>%                                                  # count gender type
  mutate(Prc = round(n/sum(n),2)) %>%            # update variable
  ungroup() %>%                                                   # forget the grouping
  mutate(Prc_text = paste0(Prc*100, "%")) %>%
  ggplot(aes(Treatments, Prc, fill=factor(Curiosity_1)))+                     # plot
  geom_bar(position = "fill", stat = "identity")+                # add bars
  #geom_text(aes(label=Prc_text), position = position_dodge(width=1), size=4) +
  coord_flip() 

```
  
```{r}
# dependent[,2:4] <- lapply( dependent[,2:4], factor, levels=0:10)
# 
# both_likert_2 = likert(dependent[, c(2:4), drop = FALSE], grouping = dependent$Treatments)
# library(grid)
# plot(both_likert_2)
```


```{r}
#plot(both_likert_2, type = "density")
```








```{r}
# V %>%
#   ggplot() + geom_bar(aes(x = outcome, y=value, fill=col), position="stack", stat="identity") +
#   geom_bar(data=lows, aes(x = outcome, y=-value, fill=col), position="stack", stat="identity") +
#   geom_hline(yintercept = 0, color =c("white")) +
#   scale_fill_identity("Percent", labels = mylevels, breaks=legend.pal, guide="legend") + 
#   theme_fivethirtyeight() + 
#   coord_flip() +
#   labs(title=mytitle, y="",x="") +
#   theme(plot.title = element_text(size=14, hjust=0.5)) +
#   theme(axis.text.y = element_text(hjust=0)) +
#   theme(legend.position = "bottom") +
#   scale_y_continuous(breaks=seq(mymin,mymax,25), limits=c(mymin,mymax))
```

```{r}
library(sjPlot)
library(sjmisc)
#plot_likert(pilot_data$Curiosity_1)
```


### Models

#### Correlation between dependent variables

```{r}
my_cols <- ggpubr::get_palette("Dark2", 4)  
palette = ggpubr::get_palette("Dark2", 4)

panel.cor <- function(x, y){
    usr <- par("usr"); on.exit(par(usr))
    par(usr = c(0, 1, 0, 1))
    r <- round(cor(x, y), digits=2)
    txt <- paste0("R = ", r)
    cex.cor <- 0.8/strwidth(txt)
    text(0.5, 0.5, txt, cex = cex.cor * r)
}
# Customize upper panel
upper.panel<-function(x, y){
  points(x,y, pch = 19, col = my_cols[dependent$Treatments])
}
# Create the plots
pairs(dependent[,1:5], 
      lower.panel = panel.cor,
      upper.panel = upper.panel)


# 
# pairs(dependent[,1:5], pch = 19,  cex = 0.5,
#       col = palette[dependent$Treatments],
#       lower.panel=NULL)
```

#### Linear Models

```{r}
#pilot_data$Curiosity_1
m_respuestas <- lm(correct_response ~ Treatments, 
                   data = pilot_data)
m_Confidence_1 <- lm(Confidence_1 ~ Treatments, 
                   data = pilot_data)
m_InfoAbruma2_1 <- lm(InfoAbruma2_1 ~ Treatments, 
                   data = pilot_data)
m_n_clicks <- lm(n_clicks ~ Treatments, 
                   data = pilot_data)
m_Curiosity_1 <- lm(Curiosity_1 ~ Treatments, 
                   data = pilot_data)
m_tiempo_min_1click_nclick <- lm(tiempo_min_1click_nclick ~ Treatments, 
                   data = pilot_data)
```

```{r, results='asis'}
stargazer::stargazer(m_respuestas, m_Confidence_1, m_InfoAbruma2_1, m_n_clicks,m_Curiosity_1, m_n_clicks,
                     m_tiempo_min_1click_nclick,
                     type = "html")
```





```{r}

nb = length(unique(sitios_sm$pagina))
nm = length(unique(sitios_sm$t_perfil))

colors = apply(expand.grid(seq(70,40,length=nm), 100, seq(15,375,length=nb+1)[1:nb]), 1, 
               function(x) hcl(x[3],x[2],x[1]))

bar <- sitios_sm %>%
  ggplot(aes(pagina, tiempo_pag, fill=interaction(t_perfil, pagina))) + 
  geom_hline(yintercept=0, colour="grey60") +
  geom_bar(stat="identity", position = "dodge", show.legend=FALSE) +
  scale_fill_manual(values=colors) +
  facet_wrap(~ tratamientos) +
  theme_classic() +
  ggpubr::rotate_x_text()

 
bar

p <- sitios_sm %>%
  ggplot(aes(pagina, tiempo_pag)) + 
    geom_point(aes(color = as.factor(useridn)))
p + geom_line(aes(group = useridn, color = as.factor(useridn))) +
  facet_wrap(~ tratamientos) +
  theme(axis.text.x = element_text(angle = 45))

p + geom_line(aes(group = useridn, color = as.factor(useridn))) +
  facet_wrap(~ Treatments) +
  theme(axis.text.x = element_text(angle = 45))

```





```{r}
sitios_sm %>%
  pivot_longer(cols = c(tiempo_sin_video, tiempo_video),
               names_to = "tipo", 
               values_to = "spend_time"
               ) %>%
  ggplot(aes(pagina, spend_time)) + 
  geom_point()+
  geom_line(aes(group = useridn, fill=tipo, color = tipo), show.legend=FALSE,
            size = 1.5) +
  theme(axis.text.x = element_text(angle = -45)) +
  facet_wrap(~Treatments)
```
```{r}
ss <- sitios_sm %>%
  pivot_longer(cols = c(tiempo_sin_video, tiempo_video),
               names_to = "tipo", 
               values_to = "spend_time"
               )  %>%
  mutate(tipo = relevel(as.factor(tipo), "tiempo_video"),
         spend_time = as.numeric(spend_time))

ss %>% ggplot(aes(spend_time, pagina)) + 
  geom_col() +
  theme(axis.text.x = element_text(angle = -45)) +
  coord_cartesian(ylim = c(min(ss$spend_time), max(ss$spend_time)))

a <- ss %>% ggplot(aes(pagina, spend_time, fill = tipo)) + 
  geom_col() +
  scale_y_continuous() +
  theme(axis.text.x = element_text(angle = -45)) 
a
b <- a$data
```
